### ISSUE TITLE
Bigger Font Size on Map View Screen 

### ISSUE THREAD

**Issue by HerrRuin** [andan67/wormnav#11]
Hello Andan,

Would It be possible to make an option to change Font Size on Map View Screen?

Double size would be perfect.
Maybe you can make an option to change in percentage?

While driving the Elapsed time and distance on top is to small for a quick view.

Many thanks Stephan

**Comment by andan67** [comment]
-->Hello Stephan, The available font sizes that can be used are limited and depend on the device.Thus a percentage size change is not possible. Instead, I’m thinking of introducing an option to set the next larger available font size.Could you please let me know which device you are you using? ThanksAndreas  Von: HerrRuinGesendet: Montag, 26. Juli 2021 19:47An: andan67/wormnavCc: SubscribedBetreff: [andan67/wormnav] Bigger Font Size on Map View Screen (#11) Hello Andan,Would It be possible to make an option to change Font Size on Map View Screen?Double size would be perfect.Maybe you can make an option to change in percentage?While driving the Elapsed time and distance on top is to small for a quick view.Many thanks Stephan—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HerrRuin** [comment]
Hello Andreas,

I use a Garmin vivoactive 3 Watch.
![16277322106306975075101792525878](https://user-images.githubusercontent.com/6007935/127738992-fd637abf-0785-495f-a84b-f3338c9277d0.jpg)

:)

**Comment by andan67** [comment]
I've just released a new version 1.5.7 that allows using a larger font size within the track view.
This can be enabled under the menu entry Course|Large font.

**Comment by HerrRuin** [comment]
How can I see the app version on the watch?
Sorry, I only see under Course the option Update period, Info and Delete. But no Font.

Did I anything wrong?

**Comment by andan67** [comment]
It might take a while until the new version is actually available via download, regardless of the version number that is actually shown in the store. I’ve just managed to install the latest version via store, so I’d suggest that you retry the installation.The app currently does not provide its version number (that is is on my todo list).  Von: HerrRuinGesendet: Sonntag, 1. August 2021 12:34An: andan67/wormnavCc: andan67; State changeBetreff: Re: [andan67/wormnav] Bigger Font Size on Map View Screen (#11) How can I see the app version on the watch?Sorry, I only see under Course the option Update period, Info and Delete. But no Font.Did I anything wrong?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HerrRuin** [comment]
Genial! Many thanks. Perfect! 😁

![16278541199715850215573349253215](https://user-images.githubusercontent.com/6007935/127786129-cd57c3fb-e8f5-4b9b-9ae6-9581de9fe2e2.jpg)

**Comment by alsama** [comment]
Great option.
Thanks too.

![IMG_20210802_131531~2.jpg](https://user-images.githubusercontent.com/28567374/127854210-5df5ca50-652f-4e43-a05a-15c072fb30e1.jpg)
